name: ExpressJS API CI/CD pipeline.
on: [push]
permissions:
  contents: read

# This workflow will build a Node.js project, run tests (if any), and then publish a Docker image to Amazon ECR.
# For more information, see https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
