name: ExpressJS API CI/CD pipeline.
on: [push]
permissions:
  contents: read

# This workflow will build a Node.js project, run tests (if any), and then publish a Docker image to Amazon ECR.
# For more information, see https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  package_docker_image:
    name: Docker & ECR repository
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push
      run: |

        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest .

